networks:
  dev:
    driver: bridge

services:
  nginx:
    image: nginx:stable-alpine
    ports:
      - "80:80"
    volumes:
      - './nginx.conf:/etc/nginx/nginx.conf'
    depends_on:
      - ssobe
    restart: always
    networks:
      - dev
      
  ssobe:
    image: askhadsabilov/ssobe:latest
    container_name: ssobe
    volumes:
      - ./config.yaml:/app/config.yaml  # Монтирование файла с хоста в контейнер
    ports:
      - "4000:4000"
    restart: always
    networks:
      - dev
